language: python

python:
  - "3.10"

# Update pip to the latest version
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - python --version
  - pip install -U pip

install:
  - pip install -r requirements.txt

script:
   - python -m unittest tests/multiplication_tests.py

deploy:
  provider: pypi
  username: "__token__"
  password: "$PYPI_TOKEN"
  on:
    branch: master